services:
    client:
        build: ./client
        ports:
            - 3000:3000
        volumes: 
            - ./client/src/:/app/src/
    server:
        build: ./server
        ports:
            - 5050:5000
        environment:
            CHOKIDAR_USEPOLLING: 'true'
        command: npm run dev
        volumes: 
            - ./server/src/:/app/src/
    mongodb:
        image: mongo
        volumes: 
            - ./data:/data/db